### ISSUE TITLE
Add copy image by right-click, add multi-selection 

### ISSUE THREAD

**Issue by vacekj** [MochiDiffusion/MochiDiffusion#146]
### Running Latest Version

- [X] I am running the latest version

### What do you want Mochi Diffusion to do?

Hello, thank you for this awesome tool! I started a $5 monthly sponsorship to hopefully help motivate you to continue the great work.

I have two feature requests that would greatly improve my workflow with Mochi Diffusion. 
First is to add a Copy image option to the right-click menu of individual items. This would simply copy the image to clipboard.
Second is to add multi-selection to the "canvas", so that I can select multiple images and then save just those images, contrary to saving all of them, or manually one-by one. 

Thank you!

### Why do you think this should be added?

I think this is a common action that users take, that currently isn't very ergonomic.

**Comment by godly-devotion** [comment]
Btw if you open an image in Quick Look and right click on the image, it will give you the option to Copy (and sometimes Copy Subject). A nice workaround you can use for now.

**Comment by vzsg** [comment]
That's what I've been doing too :)

---

I have the copy command implemented locally that needs to be aligned with the new code layout. I'll put up a PR with it later, without multi-selection (which I'm also working on behind the scenes, but it's nowhere near ready).

**Comment by pravdomil** [comment]
it would be great to
just copy selected images by pressing Cmd+C
now it is disabled

<img width="234" alt="image" src="https://github.com/godly-devotion/MochiDiffusion/assets/2387356/188247a4-db37-4804-bb98-b68857e25d19">

**Comment by pravdomil** [comment]
reopen
