### ISSUE TITLE
Favorites

### ISSUE THREAD

**Issue by stuartjmoore** [MochiDiffusion/MochiDiffusion#241]
### Running Latest Version

- [X] I am running the latest version

### What do you want Mochi Diffusion to do?

The ability to “favorite” (or otherwise mark) select images for reference later.

I can help implement such a feature.

### Why do you think this should be added?

It can be easy to generate _a lot_ of images. It would be nice to be able to get back to the best few.

**Comment by atemiz** [comment]
I think a feature like albums in photo apps could be much more useful in terms of organizing images. There may be more than one solution on how to implement this feature, but I think the easiest method is subfolder support for the images folder.

**Comment by jupdike** [comment]
Aha! I think I just built this: https://github.com/MochiDiffusion/MochiDiffusion/pull/451
