### ISSUE TITLE
The starting image size doesn't match the size of the image that will be generated

### ISSUE THREAD

**Issue by pravdomil** [MochiDiffusion/MochiDiffusion#393]
1. download https://huggingface.co/coreml-community/coreml-stable-diffusion-v1-5/tree/main
2. generate some image
3. use that image as starting image
4. press Generate
5. `The starting image size doesn't match the size of the image that will be generated`

M1@16GB@v5.0

**Comment by pravdomil** [comment]
that's maybe because it does not have controlnet thing

**Comment by jupdike** [comment]
It might be missing Image2Image. The model needs img2img to work.
