### ISSUE TITLE
Generation speed massively decreased

### ISSUE THREAD

**Issue by velolala** [MochiDiffusion/MochiDiffusion#433]
### Processor

M1 (or later)

### Memory

32GB

### What happened?

Hi there and thanks for MochiDiffusion.

I have a question regarding what may have impacted the generation speed on my M1 Pro. Yesterday I could generate pictures with the settings as below in approximately 12 seconds. I was blown away by the speed! However, today with the same settings (via `Copy Options to Sidebar`) it takes about 45 seconds. Do you have any idea, what may be the reason for this?
```
Date:
28. May 2024 at 23:04:16

Model:
stable-diffusion-v2.1-base_split-einsum_compiled

Size:
2048 x 2048 (Upscaled using RealESRGAN)

Include in Image:
cowboy fashion

Exclude from Image:


Seed:
1957878024

Steps:
12

Guidance Scale:
11.0

Scheduler:
DPM-Solver++

ML Compute Unit:
CPU & Neural Engine
```

**Comment by gdbing** [comment]
Your ML compute unit is set to `CPU & Neural Engine`, is it possible that you changed it from `Auto` or `CPU & GPU` in settings? 

You could try turning off Reduce Memory Usage  and Show Image Preview in settings, both of those have an impact on generation speed, but I think the ML Compute Unit is the most likely culprit.
