### ISSUE TITLE
changed code signature in release 5.2?

### ISSUE THREAD

**Issue by suschizu** [MochiDiffusion/MochiDiffusion#459]
### Processor

M1 (or later)

### Memory

8GB

### What happened?

hello - I've noticed that the code signature has changed between version 5.1 and 5.2 - can anyone confirm this? 
Thank you!

### Crash Log

```shell
EXPECTED 'Joshua Park (TCQ6328PP6)' 
FOUND 'Graham Bing (9VV558X8J3)'
```

**Comment by gdbing** [comment]
Yes, hello, I’m Graham Bing. Joshua (@godly-devotion) wanted to step back from Mochi and so he passed on maintainership to me a few months ago.

If you have any questions or concerns, please let me know.

**Comment by suschizu** [comment]
great - thanks for the clarification!
